### ISSUE TITLE
关于test_vecMea_noBias的疑问

### ISSUE THREAD

**Issue by mocibb** [WangWeixin442/attitude-kalman-filter#2]
测试test_vecMea_noBias中给定了两个参考方向，由于正交关系给定两个，第三个就确定了（两者叉乘）。
这样跟给定旋转没有区别。

**Comment by WangWeixin442** [comment]
是这样的没错。不过因为有误差，两个参考方向存在过约束的情况，要用 QUEST 或者 svd 估计出一个最优的旋转。

**Comment by mocibb** [comment]
明白了哈，感谢。
如果我只给出加速度的观测，感觉按照现在的代码框架不是很好改呢。

**Comment by WangWeixin442** [comment]
最近添加了单个矢量测量的情况，参考12月11号的commit
